# SwiftLint Configuration

excluded:

included:
  - Sources
  - Tests

opt_in_rules:

disabled_rules:

line_length:
  warning: 100
  error: 120
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 800
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500
  ignores_comments: true
  ignores_empty_lines: true

function_body_length:
  warning: 40
  error: 60
  ignores_comments: true

identifier_name:
  min_length:
    error: 3
  max_length:
    warning: 40
  excluded:
    - id

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 8
  error: 10
