disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count

included:
  - Source

excluded:
  - Carthage
  - Pods
  - Mesmerize/


line_length:
  warning: 101
  error: 120

type_name:
  min_length: 3
  max_length: 40
